/*
 * EditEncoders.java
 *
 * Created on 14 de Janeiro de 2008, 16:10
 */
package org.botbeans.shapes.dialogs;

import org.netbeans.api.visual.widget.Widget;
import org.botbeans.shapes.nodes.GenericNode;
import org.botbeans.shapes.utilities.ShapesUtilities;
import org.openide.util.ImageUtilities;

/**
 *
 * @author  Apocas
 */
public class EditEncoders extends javax.swing.JFrame {

    GenericNode node;
    Widget widget;

    /** Creates new form EditEncoders */
    public EditEncoders(Widget widgetf, GenericNode nodef) {
        initComponents();
        node = nodef;
        widget = widgetf;
        this.setVisible(true);

        this.setIconImage(ImageUtilities.loadImage(ShapesUtilities.icons_path + "Computer_File_097.gif", true));

        // tempo_texto.setText(String.valueOf(node.getAtributo()));
        //velocidade_texto.setText(String.valueOf(node.getVelocidade()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tempo_texto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        velocidade_texto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.title")); // NOI18N
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(550, 200, 0, 0));
        setResizable(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.jLabel1.text_1")); // NOI18N

        tempo_texto.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.tempo_texto.text")); // NOI18N
        tempo_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_textoActionPerformed(evt);
            }
        });

        jLabel2.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.jLabel2.text_1")); // NOI18N

        velocidade_texto.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.velocidade_texto.text_1")); // NOI18N

        jLabel3.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.jLabel3.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.jLabel4.text_1")); // NOI18N

        botao.setText(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.botao.text_1")); // NOI18N
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botao, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(velocidade_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(velocidade_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel4.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(EditEncoders.class, "EditEncoders.jLabel4.text_1")); // NOI18N

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tempo_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempo_textoActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        int velo = Integer.parseInt(velocidade_texto.getText());
        try {
            if (velo < 0 || velo > 100) {
                throw new NullPointerException();
            }
            //    node.setVelocidade(velo);
        } catch (Exception ex) {
            // new ErroDialog("Inserir numero inteiro (0-100%)");
            flag = 1;
        }
        try {
            //  node.setAtributo(Integer.parseInt(tempo_texto.getText()));
        } catch (Exception ex) {
            //new ErroDialog("Inserir numero inteiro.");
            flag = 1;
        }
        //((IconNodeWidget) widget).setLabel("Enc:" + node.getAtributo() + ",Velo:" + node.getVelocidade());

        if (flag == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tempo_texto;
    private javax.swing.JTextField velocidade_texto;
    // End of variables declaration//GEN-END:variables
}
