/*
 * EditTempo.java
 *
 * Created on 11 de Janeiro de 2008, 16:44
 */
package org.botbeans.shapes.dialogs;

import org.netbeans.api.visual.widget.Widget;
import org.botbeans.shapes.nodes.GenericNode;
import org.botbeans.shapes.utilities.ShapesUtilities;
import org.openide.util.ImageUtilities;

/**
 *
 * @author  Apocas
 */
public class EditTempo extends javax.swing.JFrame {

    GenericNode node;
    Widget widget;

    /** Creates new form EditTempo */
    public EditTempo(Widget widgetf, GenericNode nodef) {
        initComponents();
        node = nodef;
        widget = widgetf;
        this.setVisible(true);

        this.setIconImage(ImageUtilities.loadImage(ShapesUtilities.icons_path + "Computer_File_097.gif", true));

//        tempo_texto.setText(String.valueOf(node.getAtributo()));
//        velocidade_texto.setText(String.valueOf(node.getVelocidade()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tempo_texto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        velocidade_texto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.title")); // NOI18N
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(550, 200, 0, 0));
        setResizable(false);

        botao.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.botao.text")); // NOI18N
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        jLabel1.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.jLabel1.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.jLabel2.text")); // NOI18N

        tempo_texto.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.tempo_texto.text")); // NOI18N
        tempo_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_textoActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.jLabel3.text")); // NOI18N

        velocidade_texto.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.velocidade_texto.text")); // NOI18N

        jLabel4.setText(org.openide.util.NbBundle.getMessage(EditTempo.class, "EditTempo.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tempo_texto))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(velocidade_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)))
                    .addComponent(botao, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(velocidade_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(botao)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tempo_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_textoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_tempo_textoActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        int velo = Integer.parseInt(velocidade_texto.getText());
        try {
            if (velo < 0 || velo > 100) {
                throw new NullPointerException();
            }
//            node.setVelocidade(velo);
        } catch (Exception ex) {
            //new ErroDialog("Inserir numero inteiro (0-100%)");
            flag = 1;
        }
        try {
//            node.setAtributo(Integer.parseInt(tempo_texto.getText()));
        } catch (Exception ex) {
            //new ErroDialog("Inserir numero inteiro.");
            flag = 1;
        }
//        ((IconNodeWidget) widget).setLabel("Tmp:" + node.getAtributo() + ",Velo:" + node.getVelocidade());

        if (flag == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoActionPerformed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tempo_texto;
    private javax.swing.JTextField velocidade_texto;
    // End of variables declaration//GEN-END:variables
}
