/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.botbeans.shapes;

import java.util.HashMap;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//org.botbeans.shapes//Memory//EN",
autostore = false)
@TopComponent.Description(preferredID = "MemoryTopComponent",
iconBase = "org/botbeans/shapes/icons/memory.png",
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "properties", openAtStartup = false)
@ActionID(category = "Window", id = "org.botbeans.shapes.MemoryTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(displayName = "#CTL_MemoryAction",
preferredID = "MemoryTopComponent")
public final class MemoryTopComponent extends TopComponent {

    private final MemoryTela mt;

    public MemoryTopComponent() {
        initComponents();
        setName(NbBundle.getMessage(MemoryTopComponent.class, "CTL_MemoryTopComponent"));
        setToolTipText(NbBundle.getMessage(MemoryTopComponent.class, "HINT_MemoryTopComponent"));
        putClientProperty(TopComponent.PROP_KEEP_PREFERRED_SIZE_WHEN_SLIDED_IN, Boolean.TRUE);

        mt = new MemoryTela(null);
        jPanel1.add(mt);
    }

    public static MemoryTopComponent findInstance() {
        for (TopComponent tc : TopComponent.getRegistry().getOpened()) {
            if (tc instanceof MemoryTopComponent) {
                return (MemoryTopComponent) tc;
            }
        }
        
        return null;
    }
    
    public void updateMemory(HashMap m) {
        mt.setMemory(m);
        mt.repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());
        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }
}
