/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Configuration.java
 *
 * Created on 7/Jan/2010, 18:46:36
 */
package org.botbeans.shapes.dialogs;

import java.awt.Toolkit;
import org.botbeans.shapes.ShapeTopComponent;
import org.botbeans.shapes.utilities.ShapesUtilities;
import org.openide.util.ImageUtilities;
import org.openide.windows.TopComponent;

/**
 *
 * @author Apocas
 */
public class Configuration extends javax.swing.JFrame {

    /** Creates new form Configuration */
    public Configuration() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        combo_sonar = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        combo_comp = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        combo_sound = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.title")); // NOI18N
        setAlwaysOnTop(true);
        setIconImage(ImageUtilities.loadImage(org.botbeans.shapes.utilities.ShapesUtilities.icons_path + "Computer_File_097.gif"));
        setResizable(false);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel7.border.title"))); // NOI18N
        jPanel7.setLayout(new java.awt.GridLayout(0, 2));

        jLabel7.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel7.text")); // NOI18N
        jPanel7.add(jLabel7);

        jTextField3.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jTextField3.text")); // NOI18N
        jPanel7.add(jTextField3);

        jLabel8.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel8.text")); // NOI18N
        jPanel7.add(jLabel8);

        jTextField4.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jTextField4.text")); // NOI18N
        jPanel7.add(jTextField4);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel8);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel12);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel10);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel14);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel11);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 49, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel13);

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        jPanel1.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel4.border.title"))); // NOI18N
        jPanel4.setToolTipText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel4.toolTipText")); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(0, 2));

        jLabel9.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel9.text")); // NOI18N
        jPanel4.add(jLabel9);

        combo_sonar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        combo_sonar.setSelectedIndex(2);
        jPanel4.add(combo_sonar);

        jLabel10.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel10.text")); // NOI18N
        jPanel4.add(jLabel10);

        combo_comp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        jPanel4.add(combo_comp);

        jLabel11.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel11.text")); // NOI18N
        jPanel4.add(jLabel11);

        combo_sound.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4" }));
        combo_sound.setSelectedIndex(1);
        jPanel4.add(combo_sound);

        jPanel1.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel5.border.title"))); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(0, 2));

        jLabel3.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel3.text")); // NOI18N
        jPanel5.add(jLabel3);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        jComboBox1.setSelectedIndex(1);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox1);

        jLabel4.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel4.text")); // NOI18N
        jPanel5.add(jLabel4);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox2);

        jLabel12.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel12.text")); // NOI18N
        jPanel5.add(jLabel12);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C" }));
        jComboBox3.setSelectedIndex(2);
        jComboBox3.setEnabled(false);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel5.add(jComboBox3);

        jPanel1.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel6.border.title"))); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(0, 3));

        jLabel1.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel1.text")); // NOI18N
        jPanel6.add(jLabel1);

        jTextField1.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jTextField1.text")); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField1);

        jLabel5.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel5.text")); // NOI18N
        jPanel6.add(jLabel5);

        jLabel2.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel2.text")); // NOI18N
        jPanel6.add(jLabel2);

        jTextField2.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jTextField2.text")); // NOI18N
        jPanel6.add(jTextField2);

        jLabel6.setText(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jLabel6.text")); // NOI18N
        jPanel6.add(jLabel6);

        jPanel1.add(jPanel6);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(Configuration.class, "Configuration.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TopComponent tc = TopComponent.getRegistry().getActivated();
        if (tc instanceof ShapeTopComponent) {
            ((ShapeTopComponent) tc).setEndereco_server(jTextField3.getText());
            ((ShapeTopComponent) tc).setPorta_server(Integer.parseInt(jTextField4.getText()));
            ((ShapeTopComponent) tc).sendConfig(Float.parseFloat(jTextField2.getText()), Float.parseFloat(jTextField1.getText()), jComboBox1.getSelectedIndex()+1, jComboBox2.getSelectedIndex()+1, combo_sonar.getSelectedIndex()+1,combo_comp.getSelectedIndex()+1,combo_sound.getSelectedIndex()+1);
        } else {
            Toolkit.getDefaultToolkit().beep();
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        setThird();
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        setThird();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    public void setThird(){
        int aux =  jComboBox1.getSelectedIndex() + jComboBox2.getSelectedIndex();
        switch(aux){
            case 1:
                jComboBox3.setSelectedIndex(2);
                break;
            case 2:
                jComboBox3.setSelectedIndex(1);
                break;
            case 3:
                jComboBox3.setSelectedIndex(0);
                break;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox combo_comp;
    private javax.swing.JComboBox combo_sonar;
    private javax.swing.JComboBox combo_sound;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
