/*
 * EditSonar.java
 *
 * Created on 14 de Janeiro de 2008, 16:13
 */
package org.botbeans.shapes.dialogs;

import org.netbeans.api.visual.widget.Widget;
import org.botbeans.shapes.nodes.GenericNode;
import org.botbeans.shapes.utilities.ShapesUtilities;
import org.openide.util.ImageUtilities;

/**
 *
 * @author  Apocas
 */
public class EditSonar extends javax.swing.JFrame {

    GenericNode node;
    Widget widget;

    /** Creates new form EditSonar */
    public EditSonar(Widget widgetf, GenericNode nodef) {
        initComponents();
        node = nodef;
        widget = widgetf;
        this.setVisible(true);

        this.setIconImage(ImageUtilities.loadImage(ShapesUtilities.icons_path + "Computer_File_097.gif", true));

//        tempo_texto.setText(String.valueOf(node.getAtributo()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tempo_texto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        botao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(EditSonar.class, "EditSonar.title")); // NOI18N
        setBounds(new java.awt.Rectangle(550, 200, 0, 0));
        setIconImage(ImageUtilities.loadImage(ShapesUtilities.icons_path + "Computer_File_097.gif"));
        setResizable(false);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(EditSonar.class, "EditSonar.jLabel1.text")); // NOI18N

        tempo_texto.setText(org.openide.util.NbBundle.getMessage(EditSonar.class, "EditSonar.tempo_texto.text")); // NOI18N
        tempo_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_textoActionPerformed(evt);
            }
        });

        jLabel3.setText(org.openide.util.NbBundle.getMessage(EditSonar.class, "EditSonar.jLabel3.text")); // NOI18N

        botao.setText(org.openide.util.NbBundle.getMessage(EditSonar.class, "EditSonar.botao.text")); // NOI18N
        botao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tempo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tempo_texto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botao)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void tempo_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempo_textoActionPerformed

    private void botaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoActionPerformed
        // TODO add your handling code here:
        int flag = 0;
        try {
//            node.setAtributo(Integer.parseInt(tempo_texto.getText()));
        } catch (Exception ex) {
            //  new ErroDialog("Inserir numero inteiro.");
            flag = 1;
        }
//        ((IconNodeWidget) widget).setLabel("Dist:" + node.getAtributo());

        if (flag == 0) {
            this.dispose();
        }
    }//GEN-LAST:event_botaoActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField tempo_texto;
    // End of variables declaration//GEN-END:variables
}
